### ISSUE TITLE
Mists of Pandaria TODO list

### ISSUE THREAD

**Issue by cybrann** [MoPSource/MopCore547#55]
- [ ] Scenario system (#49)
- [ ] Challenge Mode dungeons (#54)
- [ ] Legendary Questline (#50)
- [ ] Dungeons rewrite (#34)
- [ ] Raids rewrite (#34)
- [ ] Tillers Farm
- [ ] Patch 5.1: Lion's Landing (A) and Domination Point (H)
- [ ] Patch 5.4: Timeless Isle (#29)
- [ ] Patch 5.2: Isle of Thunder
- [ ] Vale of Eternal Blossoms introduction questline
- [ ] Klaxxi paragons questline
- [ ] Pathfinding (#48)

(Update this list whenever you encounter something that needs to be done for Mists of Pandaria expansion)
